const L = {
  en:{hint:'Tap any part of your site to change it.',edit:'Edit',browse:'Browse',review:'Review',send:'Send changes',update:'Save changes',
    count:n=>n===1?'1 change':n+' changes',editMe:'Edit me',edited:'Edited',save:'Save',undo:'Undo change',
    big:'This is a bigger change (layout, new section)',addNote:'Add a note',notePh:'Anything we should know?',
    imgQ:'What should go here?',imgPh:'Paste a link to a photo, or describe it. You can also email photos to hello@mrspace.online.',
    locked:'We already started on this one. Message us if it needs to change.',sheet:'Your changes',empty:'Nothing yet. Tap a part of your site to change it.',
    other:'Anything else?',otherPh:'Ideas, missing pieces, things you want us to add.',name:'Your name',email:'Email (we send your edit link here)',
    sent:'Sent. We will take it from here.',updated:'Saved.',mailed:'Keep your private link below to return and update your request. Email delivery depends on the mail setup.',
    savedV:v=>'Your changes are updated. This is version '+v+'.',noChange:'Nothing changed since last time.',
    revise:'Change my answers',copy:'Copy link',copied:'Link copied',needOne:'Make at least one change first.',needEmail:'Enter an email so we can send your link.',
    err:'Could not send. Check your connection and try again.',bad:'This link is not valid. Ask us for a new one.',
    elsewhere:'On another page',general:'General note',inProgress:'In progress',quota:q=>q.small_quota?('This month: '+q.small_used+' of '+q.small_quota+' small changes used.'):''},
  tr:{hint:'Değiştirmek istediğin yere dokun.',edit:'Düzenle',browse:'Gez',review:'Gözden geçir',send:'Değişiklikleri gönder',update:'Değişiklikleri kaydet',
    count:n=>n+' değişiklik',editMe:'Düzenle',edited:'Düzenlendi',save:'Kaydet',undo:'Geri al',
    big:'Bu büyük bir değişiklik (düzen, yeni bölüm)',addNote:'Not ekle',notePh:'Bilmemiz gereken bir şey var mı?',
    imgQ:'Buraya ne gelsin?',imgPh:'Fotoğraf linki yapıştır ya da anlat. Fotoğrafları hello@mrspace.online adresine de atabilirsin.',
    locked:'Bunun üzerinde çalışmaya başladık. Değişmesi gerekiyorsa bize yaz.',sheet:'Değişikliklerin',empty:'Henüz yok. Değiştirmek için sitende bir yere dokun.',
    other:'Eklemek istediğin başka bir şey?',otherPh:'Fikirler, eksikler, eklenmesini istediğin şeyler.',name:'Adın',email:'E-posta (düzenleme linkini buraya yollarız)',
    sent:'Gönderildi. Gerisi bizde.',updated:'Kaydedildi.',mailed:'Talebine dönmek için aşağıdaki özel bağlantıyı sakla. E-posta teslimatı posta kurulumuna bağlıdır.',
    savedV:v=>'Değişikliklerin güncellendi. Bu '+v+'. sürüm.',noChange:'Son seferden beri bir şey değişmedi.',
    revise:'Cevaplarımı değiştir',copy:'Linki kopyala',copied:'Link kopyalandı',needOne:'Önce en az bir değişiklik yap.',needEmail:'Linki yollayabilmemiz için e-posta yaz.',
    err:'Gönderilemedi. Bağlantını kontrol edip tekrar dene.',bad:'Bu link geçerli değil. Bizden yenisini iste.',
    elsewhere:'Başka sayfada',general:'Genel not',inProgress:'Üzerinde çalışılıyor',quota:q=>q.small_quota?('Bu ay: '+q.small_quota+' küçük değişikliğin '+q.small_used+' tanesi kullanıldı.'):''},
  es:{hint:'Toca cualquier parte de tu sitio para cambiarla.',edit:'Editar',browse:'Navegar',review:'Revisar',send:'Enviar cambios',update:'Guardar cambios',
    count:n=>n===1?'1 cambio':n+' cambios',editMe:'Editar',edited:'Editado',save:'Guardar',undo:'Deshacer',
    big:'Es un cambio grande (diseño, nueva sección)',addNote:'Añadir una nota',notePh:'¿Algo que debamos saber?',
    imgQ:'¿Qué debería ir aquí?',imgPh:'Pega un enlace a una foto o descríbela. También puedes enviar fotos a hello@mrspace.online.',
    locked:'Ya empezamos con esto. Escríbenos si hay que cambiarlo.',sheet:'Tus cambios',empty:'Nada aún. Toca una parte de tu sitio para cambiarla.',
    other:'¿Algo más?',otherPh:'Ideas, cosas que faltan, lo que quieras añadir.',name:'Tu nombre',email:'Email (aquí enviamos tu enlace)',
    sent:'Enviado. Nosotros nos encargamos.',updated:'Guardado.',mailed:'Guarda el enlace privado de abajo para volver a tu solicitud. El envío por email depende de la configuración.',
    savedV:v=>'Tus cambios están actualizados. Versión '+v+'.',noChange:'No cambió nada desde la última vez.',
    revise:'Cambiar mis respuestas',copy:'Copiar enlace',copied:'Enlace copiado',needOne:'Haz al menos un cambio primero.',needEmail:'Escribe un email para enviarte tu enlace.',
    err:'No se pudo enviar. Revisa tu conexión e inténtalo de nuevo.',bad:'Este enlace no es válido. Pídenos uno nuevo.',
    elsewhere:'En otra página',general:'Nota general',inProgress:'En curso',quota:q=>q.small_quota?('Este mes: '+q.small_used+' de '+q.small_quota+' cambios pequeños usados.'):''},
  de:{hint:'Tippe auf einen Teil deiner Seite, um ihn zu ändern.',edit:'Bearbeiten',browse:'Ansehen',review:'Prüfen',send:'Änderungen senden',update:'Änderungen speichern',
    count:n=>n===1?'1 Änderung':n+' Änderungen',editMe:'Bearbeiten',edited:'Bearbeitet',save:'Speichern',undo:'Rückgängig',
    big:'Größere Änderung (Layout, neuer Abschnitt)',addNote:'Notiz hinzufügen',notePh:'Sollten wir etwas wissen?',
    imgQ:'Was soll hier hin?',imgPh:'Link zu einem Foto einfügen oder beschreiben. Fotos auch an hello@mrspace.online.',
    locked:'Daran arbeiten wir schon. Schreib uns, wenn es sich ändern soll.',sheet:'Deine Änderungen',empty:'Noch nichts. Tippe auf einen Teil deiner Seite.',
    other:'Sonst noch etwas?',otherPh:'Ideen, Fehlendes, Wünsche.',name:'Dein Name',email:'E-Mail (hierhin senden wir deinen Link)',
    sent:'Gesendet. Ab hier übernehmen wir.',updated:'Gespeichert.',mailed:'Bewahre den privaten Link unten für deine Anfrage auf. E-Mail-Versand hängt von der Einrichtung ab.',
    savedV:v=>'Deine Änderungen sind aktualisiert. Version '+v+'.',noChange:'Seit dem letzten Mal hat sich nichts geändert.',
    revise:'Antworten ändern',copy:'Link kopieren',copied:'Link kopiert',needOne:'Mach zuerst mindestens eine Änderung.',needEmail:'Gib eine E-Mail an, damit wir dir den Link senden.',
    err:'Senden fehlgeschlagen. Prüfe deine Verbindung und versuch es erneut.',bad:'Dieser Link ist ungültig. Frag uns nach einem neuen.',
    elsewhere:'Auf einer anderen Seite',general:'Allgemeine Notiz',inProgress:'In Arbeit',quota:q=>q.small_quota?('Diesen Monat: '+q.small_used+' von '+q.small_quota+' kleinen Änderungen genutzt.'):''},
  fr:{hint:'Touchez une partie de votre site pour la modifier.',edit:'Modifier',browse:'Parcourir',review:'Vérifier',send:'Envoyer',update:'Enregistrer',
    count:n=>n===1?'1 modification':n+' modifications',editMe:'Modifier',edited:'Modifié',save:'Enregistrer',undo:'Annuler',
    big:'C\'est un gros changement (mise en page, nouvelle section)',addNote:'Ajouter une note',notePh:'Quelque chose à savoir ?',
    imgQ:'Que mettre ici ?',imgPh:'Collez un lien vers une photo ou décrivez-la. Vous pouvez aussi envoyer des photos à hello@mrspace.online.',
    locked:'Nous avons déjà commencé. Écrivez-nous s\'il faut le changer.',sheet:'Vos modifications',empty:'Rien pour l\'instant. Touchez une partie de votre site.',
    other:'Autre chose ?',otherPh:'Idées, éléments manquants, ajouts souhaités.',name:'Votre nom',email:'Email (nous y envoyons votre lien)',
    sent:'Envoyé. On s\'occupe du reste.',updated:'Enregistré.',mailed:'Conservez le lien privé ci-dessous pour retrouver votre demande. L’envoi par e-mail dépend de la configuration.',
    savedV:v=>'Vos modifications sont à jour. Version '+v+'.',noChange:'Rien n\'a changé depuis la dernière fois.',
    revise:'Modifier mes réponses',copy:'Copier le lien',copied:'Lien copié',needOne:'Faites d\'abord au moins une modification.',needEmail:'Indiquez un email pour recevoir votre lien.',
    err:'Envoi impossible. Vérifiez la connexion et réessayez.',bad:'Ce lien n\'est pas valide. Demandez-nous en un nouveau.',
    elsewhere:'Sur une autre page',general:'Note générale',inProgress:'En cours',quota:q=>q.small_quota?('Ce mois-ci : '+q.small_used+' sur '+q.small_quota+' petites modifications.'):''}
};
const rufcutEnglish = new URLSearchParams(location.search).get('site')==='rufcut'||new URLSearchParams(location.search).get('preview')==='rufcut';
const lang = (()=>{ if(rufcutEnglish)return 'en'; let p=null; try{p=localStorage.getItem('ms_lang')}catch(e){}
  const c=(p||navigator.language||'en').slice(0,2).toLowerCase(); return L[c]?c:'en'; })();
const t = L[lang]; document.documentElement.lang = lang;
const G = {
  en:{checklist:'Checklist',gTop:'Top of the page',looksGood:'Looks good',changeIt:'Change it',changeSome:'Change something',
    gTapPart:'Tap the part you want to change on your site. Press Next when you are done.',gNext:'Next',gBack:'Back',gSkip:'Skip',gList:'See the list',gHide:'Hide',
    gChanged:'You changed this part.',gOkd:'You marked this as good.',gDoneT:'All checked.',gDoneX:'Every part of your site has been looked at. Send it over and we will take it from here.',
    gLeft:n=>n===1?'1 part left to check':n+' parts left to check',hHead:'Is this how you would say it?',hText:'Read this. Does it sound like you, and is it correct?',
    hImg:'Should your own photo go here? Paste a link or describe it.',hFill:'This is a placeholder. Enter the real thing.'},
  tr:{checklist:'Kontrol listesi',gTop:'Sayfanın başı',looksGood:'Doğru',changeIt:'Değiştir',changeSome:'Bir şeyi değiştir',
    gTapPart:'Sitende değiştirmek istediğin yere dokun. Bitince İleri\'ye bas.',gNext:'İleri',gBack:'Geri',gSkip:'Atla',gList:'Listeyi gör',gHide:'Gizle',
    gChanged:'Bu kısmı değiştirdin.',gOkd:'Bunu doğru olarak işaretledin.',gDoneT:'Hepsi kontrol edildi.',gDoneX:'Sitenin her kısmına bakıldı. Gönder, gerisi bizde.',
    gLeft:n=>n+' kısım kontrol bekliyor',hHead:'Sen böyle mi söylerdin?',hText:'Bunu oku. Senin ağzından çıkmış gibi mi, doğru mu?',
    hImg:'Buraya kendi fotoğrafın mı gelsin? Link yapıştır ya da anlat.',hFill:'Bu bir yer tutucu. Gerçeğini yaz.'},
  es:{checklist:'Lista',gTop:'Inicio de la página',looksGood:'Está bien',changeIt:'Cambiar',changeSome:'Cambiar algo',
    gTapPart:'Toca la parte de tu sitio que quieres cambiar. Pulsa Siguiente al terminar.',gNext:'Siguiente',gBack:'Atrás',gSkip:'Saltar',gList:'Ver la lista',gHide:'Ocultar',
    gChanged:'Cambiaste esta parte.',gOkd:'La marcaste como correcta.',gDoneT:'Todo revisado.',gDoneX:'Revisaste cada parte de tu sitio. Envíalo y nosotros seguimos.',
    gLeft:n=>n===1?'Falta 1 parte por revisar':'Faltan '+n+' partes por revisar',hHead:'¿Lo dirías así?',hText:'Léelo. ¿Suena como tú y es correcto?',
    hImg:'¿Va aquí una foto tuya? Pega un enlace o descríbela.',hFill:'Esto es un ejemplo. Escribe el dato real.'},
  de:{checklist:'Checkliste',gTop:'Seitenanfang',looksGood:'Passt',changeIt:'Ändern',changeSome:'Etwas ändern',
    gTapPart:'Tippe auf den Teil deiner Seite, den du ändern willst. Danach auf Weiter.',gNext:'Weiter',gBack:'Zurück',gSkip:'Überspringen',gList:'Liste ansehen',gHide:'Ausblenden',
    gChanged:'Du hast diesen Teil geändert.',gOkd:'Du hast das als passend markiert.',gDoneT:'Alles geprüft.',gDoneX:'Jeder Teil deiner Seite wurde angesehen. Schick es uns, wir übernehmen.',
    gLeft:n=>n===1?'1 Teil noch offen':n+' Teile noch offen',hHead:'Würdest du es so sagen?',hText:'Lies das. Klingt es nach dir und stimmt es?',
    hImg:'Soll hier dein eigenes Foto hin? Link einfügen oder beschreiben.',hFill:'Das ist ein Platzhalter. Trag das Echte ein.'},
  fr:{checklist:'Liste',gTop:'Haut de page',looksGood:'C\'est bon',changeIt:'Modifier',changeSome:'Modifier quelque chose',
    gTapPart:'Touchez la partie de votre site à modifier. Appuyez sur Suivant ensuite.',gNext:'Suivant',gBack:'Retour',gSkip:'Passer',gList:'Voir la liste',gHide:'Masquer',
    gChanged:'Vous avez modifié cette partie.',gOkd:'Vous l\'avez marquée comme bonne.',gDoneT:'Tout est vérifié.',gDoneX:'Chaque partie de votre site a été vue. Envoyez-la, on s\'occupe du reste.',
    gLeft:n=>n===1?'1 partie à vérifier':n+' parties à vérifier',hHead:'Le diriez-vous comme ça ?',hText:'Lisez. Est-ce votre ton, et est-ce exact ?',
    hImg:'Votre propre photo ici ? Collez un lien ou décrivez-la.',hFill:'C\'est un exemple. Écrivez la vraie info.'}
};
Object.assign(t, G[lang] || G.en);

// Source order: English, Turkish, Spanish, German, French.
const editorWords = {
  editor:['Site editor','Site editörü','Editor del sitio','Website-Editor','Éditeur du site'],
  areas:['Page areas','Sayfa alanları','Áreas de la página','Seitenbereiche','Zones de la page'],
  search:['Find text or a photo…','Metin veya fotoğraf bul…','Buscar texto o foto…','Text oder Foto suchen…','Trouver un texte ou une photo…'],
  choose:['Choose an area on the left or select it on your site.','Soldan bir alan seç veya sitede üzerine dokun.','Elige un área a la izquierda o selecciónala en tu sitio.','Wähle links einen Bereich oder klicke ihn auf der Seite an.','Choisissez une zone à gauche ou directement sur le site.'],
  previewOnly:['Your preview. Changes go for review before publication.','Bu senin önizlemen. Değişiklikler yayından önce incelemeye gider.','Tu vista previa. Los cambios se revisan antes de publicarse.','Deine Vorschau. Änderungen werden vor der Veröffentlichung geprüft.','Votre aperçu. Les modifications sont vérifiées avant publication.'],
  where:['Location','Konum','Ubicación','Position','Emplacement'],
  home:['Home','Ana sayfa','Inicio','Startseite','Accueil'],
  heading:['Heading','Başlık','Título','Überschrift','Titre'],
  text:['Text','Metin','Texto','Text','Texte'],
  button:['Button','Düğme','Botón','Schaltfläche','Bouton'],
  photo:['Photo','Fotoğraf','Foto','Foto','Photo'],
  before:['Current site','Sitedeki hali','Sitio actual','Aktuelle Website','Site actuel'],
  after:['Your change','Senin değişikliğin','Tu cambio','Deine Änderung','Votre modification'],
  content:['New content','Yeni içerik','Contenido nuevo','Neuer Inhalt','Nouveau contenu'],
  upload:['Choose a photo','Fotoğraf seç','Elegir una foto','Foto auswählen','Choisir une photo'],
  uploadHint:['JPG, PNG, WebP or GIF · up to 5 MB. Keeps the site’s photo styling.','JPG, PNG, WebP veya GIF · en fazla 5 MB. Sitenin fotoğraf stili korunur.','JPG, PNG, WebP o GIF · hasta 5 MB. Conserva el estilo fotográfico del sitio.','JPG, PNG, WebP oder GIF · bis 5 MB. Der Fotostil der Seite bleibt erhalten.','JPG, PNG, WebP ou GIF · 5 Mo maximum. Le style photo du site est conservé.'],
  uploading:['Uploading photo…','Fotoğraf yükleniyor…','Subiendo foto…','Foto wird hochgeladen…','Envoi de la photo…'],
  uploadError:['Photo could not upload. Your other changes are safe. Try again or paste a photo link.','Fotoğraf yüklenemedi. Diğer değişikliklerin korunuyor. Tekrar dene veya fotoğraf linki yapıştır.','No se pudo subir la foto. Los otros cambios se conservan. Reintenta o pega un enlace.','Foto konnte nicht hochgeladen werden. Andere Änderungen bleiben erhalten. Erneut versuchen oder Fotolink einfügen.','La photo n’a pas pu être envoyée. Les autres modifications sont conservées. Réessayez ou collez un lien.'],
  uploadInvalid:['Choose a JPG, PNG, WebP or GIF smaller than 5 MB.','5 MB altında JPG, PNG, WebP veya GIF seç.','Elige un JPG, PNG, WebP o GIF de menos de 5 MB.','Wähle JPG, PNG, WebP oder GIF unter 5 MB.','Choisissez un JPG, PNG, WebP ou GIF de moins de 5 Mo.'],
  imageLink:['Photo link or instructions','Fotoğraf linki veya açıklama','Enlace o instrucciones para la foto','Fotolink oder Beschreibung','Lien photo ou instructions'],
  imageFailed:['The photo link could not be previewed. Check the link or choose a file.','Fotoğraf linki önizlenemedi. Linki kontrol et veya dosya seç.','No se pudo mostrar la foto. Revisa el enlace o elige un archivo.','Fotolink kann nicht angezeigt werden. Prüfe ihn oder wähle eine Datei.','Impossible d’afficher la photo. Vérifiez le lien ou choisissez un fichier.'],
  photoNote:['Instructions only. The current photo stays in this preview.','Yalnızca açıklama. Önizlemede mevcut fotoğraf kalır.','Solo instrucciones. La foto actual permanece en la vista previa.','Nur Beschreibung. Das aktuelle Foto bleibt in der Vorschau.','Instructions uniquement. La photo actuelle reste dans l’aperçu.'],
  saved:['Added to your draft','Taslağına eklendi','Añadido al borrador','Zum Entwurf hinzugefügt','Ajouté au brouillon'],
  local:['Draft saved on this device. Not sent yet.','Taslak bu cihazda kayıtlı. Henüz gönderilmedi.','Borrador guardado en este dispositivo. Aún no enviado.','Entwurf auf diesem Gerät gespeichert. Noch nicht gesendet.','Brouillon enregistré sur cet appareil. Pas encore envoyé.'],
  unsaved:['Editing this area. Add it to your draft to keep it.','Bu alanı düzenliyorsun. Korumak için taslağına ekle.','Editando esta área. Añádela al borrador para conservarla.','Bereich wird bearbeitet. Zum Entwurf hinzufügen, um ihn zu behalten.','Modification en cours. Ajoutez-la au brouillon pour la conserver.'],
  storageError:['This device could not save your draft. Keep this page open until you send it.','Cihaz taslağı kaydedemedi. Gönderene kadar sayfayı açık tut.','El dispositivo no pudo guardar el borrador. Mantén esta página abierta hasta enviarlo.','Entwurf konnte nicht auf dem Gerät gespeichert werden. Seite bis zum Senden offen lassen.','Cet appareil n’a pas pu enregistrer le brouillon. Gardez la page ouverte jusqu’à l’envoi.'],
  recovered:['Your unsent changes have been restored on this device.','Gönderilmemiş değişikliklerin bu cihazdan geri yüklendi.','Se restauraron los cambios sin enviar de este dispositivo.','Ungesendete Änderungen auf diesem Gerät wurden wiederhergestellt.','Vos modifications non envoyées ont été restaurées sur cet appareil.'],
  addDraft:['Add to draft','Taslağa ekle','Añadir al borrador','Zum Entwurf hinzufügen','Ajouter au brouillon'],
  backAreas:['All areas','Tüm alanlar','Todas las áreas','Alle Bereiche','Toutes les zones'],
  locate:['Show on site','Sitede göster','Mostrar en el sitio','Auf der Seite zeigen','Voir sur le site'],
  sendCheck:['Confirm the affected areas','Değişecek alanları kontrol et','Confirma las áreas afectadas','Betroffene Bereiche prüfen','Vérifiez les zones concernées'],
  submitNote:['Only the areas below will be sent for review. Your live site changes after approval.','Yalnızca aşağıdaki alanlar incelemeye gönderilir. Canlı siten onaydan sonra değişir.','Solo se envían estas áreas para revisión. Tu sitio cambia después de la aprobación.','Nur diese Bereiche werden zur Prüfung gesendet. Die Live-Seite ändert sich nach Freigabe.','Seules ces zones seront envoyées pour vérification. Le site sera modifié après approbation.'],
  receivedAreas:['Areas received for review','İnceleme için alınan alanlar','Áreas recibidas para revisión','Zur Prüfung erhaltene Bereiche','Zones reçues pour vérification'],
  discard:['Discard this edit','Bu düzenlemeyi bırak','Descartar esta edición','Bearbeitung verwerfen','Abandonner cette modification'],
  keep:['Keep editing','Düzenlemeye devam et','Seguir editando','Weiter bearbeiten','Continuer à modifier'],
  discardAsk:['This area has changes that are not in your draft. Add them or discard them before moving on.','Bu alanda henüz taslağa eklenmemiş değişiklik var. Devam etmeden taslağa ekle veya düzenlemeyi bırak.','Esta área tiene cambios sin añadir al borrador. Añádelos o descártalos antes de continuar.','Dieser Bereich enthält Änderungen außerhalb des Entwurfs. Vor dem Wechsel hinzufügen oder verwerfen.','Cette zone contient des modifications hors du brouillon. Ajoutez-les ou abandonnez-les avant de continuer.'],
  cancel:['Cancel','Vazgeç','Cancelar','Abbrechen','Annuler'],
  noResults:['No areas match your search.','Aramana uygun alan bulunamadı.','No hay áreas para esta búsqueda.','Keine passenden Bereiche gefunden.','Aucune zone ne correspond à la recherche.'],
  removed:['Change removed from your draft','Değişiklik taslaktan kaldırıldı','Cambio eliminado del borrador','Änderung aus dem Entwurf entfernt','Modification retirée du brouillon'],
  missing:['This area is unavailable on this page. Your request is still listed for review.','Bu alan bu sayfada bulunamadı. Talebin inceleme listesinde duruyor.','Esta área no está disponible en esta página. La solicitud sigue en la lista de revisión.','Dieser Bereich ist hier nicht verfügbar. Die Anfrage bleibt in der Prüfliste.','Cette zone est indisponible sur cette page. La demande reste dans la liste.'],
  currentChanged:['The current site differs from your saved original. Compare both versions before sending.','Sitenin mevcut hali kayıtlı ilk halinden farklı. Göndermeden önce ikisini karşılaştır.','El sitio actual difiere del original guardado. Compara ambas versiones antes de enviar.','Die Website weicht vom gespeicherten Original ab. Vor dem Senden beide vergleichen.','Le site diffère de l’original enregistré. Comparez les versions avant l’envoi.'],
  close:['Close','Kapat','Cerrar','Schließen','Fermer'],
  language:['Editor language','Editör dili','Idioma del editor','Editor-Sprache','Langue de l’éditeur'],
  chooseArea:['Choose an area','Alan seç','Elegir un área','Bereich wählen','Choisir une zone'],
  changes:['Changes','Değişiklikler','Cambios','Änderungen','Modifications'],
  limit:['You can send up to 40 areas, with 2,000 characters per area.','En fazla 40 alan ve alan başına 2.000 karakter gönderebilirsin.','Puedes enviar hasta 40 áreas y 2000 caracteres por área.','Bis zu 40 Bereiche mit jeweils 2.000 Zeichen senden.','Vous pouvez envoyer jusqu’à 40 zones de 2 000 caractères chacune.'],
  note:['Note','Not','Nota','Notiz','Note'],
  sending:['Sending for review…','İncelemeye gönderiliyor…','Enviando para revisión…','Wird zur Prüfung gesendet…','Envoi pour vérification…']
};
Object.assign(editorWords,{
  designReview:['This change needs design review before publication.','Bu değişiklik yayından önce tasarım incelemesi gerektirir.','Este cambio requiere revisión de diseño antes de publicarse.','Diese Änderung erfordert eine Designprüfung vor der Veröffentlichung.','Cette modification nécessite une vérification du design avant publication.'],
  demoNote:['Preview only. Nothing is sent or published. File uploads require site access.','Önizleme. Hiçbir şey gönderilmez veya yayınlanmaz. Dosya yüklemek için site erişimi gerekir.','Vista previa. No se envía ni publica nada. Subir archivos requiere acceso al sitio.','Vorschau. Nichts wird gesendet oder veröffentlicht. Datei-Uploads erfordern Website-Zugriff.','Aperçu. Rien n’est envoyé ni publié. L’envoi de fichiers nécessite un accès au site.'],
  removeText:['Remove this text','Bu metni kaldır','Quitar este texto','Diesen Text entfernen','Supprimer ce texte'],
  recoverConflict:['The server has a newer request. Choose which version to continue editing.','Sunucuda daha yeni bir talep var. Düzenlemeye hangi sürümle devam edeceğini seç.','Hay una solicitud más reciente en el servidor. Elige qué versión seguir editando.','Auf dem Server liegt eine neuere Anfrage. Wähle die Version für die weitere Bearbeitung.','Une demande plus récente existe sur le serveur. Choisissez la version à modifier.'],
  useServer:['Use server version','Sunucudaki sürümü kullan','Usar versión del servidor','Serverversion verwenden','Utiliser la version du serveur'],
  snapshotNote:['Page snapshot. Catalog and map changes use their native panels.','Sayfa görüntüsü. Katalog ve harita değişiklikleri kendi panellerinden yapılır.','Vista de la página. El catálogo y el mapa se editan en sus propios paneles.','Seitenansicht. Katalog und Karte werden in ihren eigenen Panels bearbeitet.','Aperçu de la page. Le catalogue et la carte se modifient dans leurs propres panneaux.'],
  restoreDraft:['Restore my device draft','Cihazdaki taslağımı geri yükle','Restaurar borrador del dispositivo','Geräteentwurf wiederherstellen','Restaurer le brouillon local']
});
const editorLangs=['en','tr','es','de','fr'];
Object.assign(editorWords,{
  colorPicker:['Choose the new color','Yeni rengi seç','Elige el nuevo color','Neue Farbe wählen','Choisissez la nouvelle couleur'],
  colorHex:['Color code (HEX)','Renk kodu (HEX)','Código de color (HEX)','Farbcode (HEX)','Code couleur (HEX)'],
  colorHint:['The swatch and drawing show your draft color. Add it to your draft, then send for review. The live site changes after approval.','Renk kutusu ve çizim taslak rengini gösterir. Taslağa ekle, ardından incelemeye gönder. Canlı site onaydan sonra değişir.','La muestra y el dibujo muestran el color del borrador. Añádelo al borrador y envíalo para revisión. El sitio cambia tras la aprobación.','Farbfeld und Zeichnung zeigen die Entwurfsfarbe. Zum Entwurf hinzufügen und zur Prüfung senden. Die Live-Seite ändert sich nach Freigabe.','L’échantillon et le dessin affichent la couleur du brouillon. Ajoutez-la au brouillon, puis envoyez pour vérification. Le site change après approbation.'],
  colorInvalid:['Enter a six-digit HEX color, for example #1E3466.','Altı haneli HEX renk kodu yaz, örneğin #1E3466.','Introduce un color HEX de seis dígitos, por ejemplo #1E3466.','Sechsstelligen HEX-Farbcode eingeben, zum Beispiel #1E3466.','Saisissez un code HEX à six chiffres, par exemple #1E3466.'],
  choiceRequest:['Requested change to this option','Bu seçenek için istenen değişiklik','Cambio solicitado para esta opción','Gewünschte Änderung dieser Option','Modification souhaitée pour cette option'],
  choiceHint:['Describe the change to this pattern or automatic color. It is sent for review; the drawing keeps the current pattern.','Bu desen veya otomatik renk için değişikliği tarif et. İncelemeye gönderilir; çizimde mevcut desen kalır.','Describe el cambio de este patrón o color automático. Se envía para revisión; el dibujo conserva el patrón actual.','Änderung dieses Musters oder der automatischen Farbe beschreiben. Wird zur Prüfung gesendet; die Zeichnung behält das aktuelle Muster.','Décrivez le changement du motif ou de la couleur automatique. Il sera vérifié ; le dessin conserve le motif actuel.']
});
for(const [key,values] of Object.entries(editorWords))t[key]=values[editorLangs.indexOf(lang)];
