import assert from 'node:assert/strict';import fs from 'node:fs';import {pathToFileURL} from 'node:url';import {catalogService} from './catalog-service-fixture.mjs';import {service} from './order-service-fixture.mjs';import '../assets/ms-commerce.js';
const {chromium}=await import(pathToFileURL(process.env.MS_PLAYWRIGHT_MODULE)),browser=await chromium.launch({executablePath:process.env.MS_CHROME_PATH,headless:true}),origin=process.env.MS_PREVIEW_ORIGIN||'http://127.0.0.1:4174';let count=0;const test=async(name,fn)=>{await fn();console.log('PASS '+name);count++;};
async function fixture(lang='en',width=1280){const context=await browser.newContext({locale:lang,viewport:{width,height:1000},reducedMotion:'reduce'}),square=catalogService(),orders=service(),notifications=service('notifications'),errors=[];
const setup=MsCommerce.blank();setup.countries=['US'];setup.pickup=true;await square.post({action:'commerce_save',setup});await square.post({action:'save_publication',item:'coat',publication:{section:'shop',layout:'grouped',title:'',variations:{s:{visible:true,title:''},m:{visible:true,title:''}}}});
await context.addInitScript(lang=>{localStorage.setItem('ms_lang',lang);localStorage.setItem('ms_panel',JSON.stringify({access_token:'test-session',expires_at:Date.now()/1000+3600,email:'owner@example.test'}));},lang);
await context.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(u.origin===origin)return route.continue();if(!u.hostname.endsWith('.supabase.co'))return route.abort();if(u.pathname.includes('ms-square')){const r=u.pathname.endsWith('/public')?await square.publicCatalog():await square.post(req.postDataJSON());return route.fulfill({status:r.status,body:await r.text(),contentType:'application/json'});}if(u.pathname.endsWith('ms-repair')||u.pathname.endsWith('ms-notifications')){const r=await(u.pathname.endsWith('ms-repair')?orders:notifications).post(req.postDataJSON(),{auth:true});return route.fulfill({status:r.status,body:await r.text(),contentType:'application/json'});}return route.fulfill({contentType:'application/json',body:JSON.stringify(u.pathname.endsWith('ms_my_sites')?[{slug:'rufcut',name:'Rufcut',url:origin+'/rufcut/'},{slug:'heron',name:'Heron CA',url:'https://heronca.com/'}]:{sites:[]})});});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000);await page.goto(origin+'/panel/?site=rufcut&view=commerce');await page.locator('[data-commerce-form]').waitFor();return {context,page,square,errors};}
try{
await test('Rufcut US/pickup preparation and Heron settings are separate',async()=>{const f=await fixture();assert.equal(await f.page.locator('[name=countries]').inputValue(),'US');assert.equal(await f.page.locator('[name=pickup]').isChecked(),true);assert.equal(await f.page.locator('[name=standard_base]').inputValue(),'');await f.page.locator('#sitePick').selectOption('heron');await f.page.waitForFunction(()=>document.querySelector('[data-commerce-root=heron] [name=countries]'));assert.equal(await f.page.locator('[name=countries]').inputValue(),'');assert.equal(await f.page.locator('[name=pickup]').isChecked(),false);assert.ok((await f.page.locator('.commerce h2 small').textContent()).includes('Currency pending'));assert.deepEqual(f.errors,[]);await f.context.close();});
await test('draft survives tabs, before/after names fields, failed save preserves inputs, retry persists',async()=>{const f=await fixture();await f.page.locator('[name=dispatch_days]').fill('3');assert.ok((await f.page.locator('[data-commerce-changes]').innerText()).includes('Dispatch within'));await f.page.locator('[data-v=catalog]').click();await f.page.locator('[data-v=commerce]').click();await f.page.locator('[data-commerce-form]').waitFor();assert.equal(await f.page.locator('[name=dispatch_days]').inputValue(),'3');f.square.state.failCommerce=true;await f.page.locator('[name=confirm]').check();await f.page.locator('[data-commerce-form] [type=submit]').click();await f.page.waitForFunction(()=>document.querySelector('[data-commerce-error]')?.textContent.includes('Could not save'));assert.equal(await f.page.locator('[name=dispatch_days]').inputValue(),'3');f.square.state.failCommerce=false;await f.page.locator('[data-commerce-form] [type=submit]').click();await f.page.waitForFunction(()=>document.querySelector('[data-commerce-changes]')?.textContent==='');assert.equal(f.square.state.commerce.find(s=>s.site==='rufcut').setup.dispatch_days,3);assert.deepEqual(f.errors,[]);await f.context.close();});
await test('saved product and parcel settings produce exact mixed-cart preview without payment calls',async()=>{const f=await fixture();await f.page.locator('[name=mode]').selectOption('flat');await f.page.locator('[name=standard_base]').fill('12');await f.page.locator('[name=standard_extra]').fill('3');await f.page.locator('[data-commerce-product=coat] summary').click();await f.page.locator('[data-product-field=sale]').selectOption('ready');await f.page.locator('[name=confirm]').check();await f.page.locator('[data-commerce-form] [type=submit]').click();await f.page.waitForFunction(()=>document.querySelector('[data-commerce-changes]')?.textContent==='');await f.page.locator('[data-commerce-add]').click();await f.page.locator('.commerce-quote-line select').nth(1).selectOption('m');await f.page.locator('[data-commerce-quote] [type=submit]').click();await f.page.waitForFunction(()=>document.querySelector('[data-commerce-result]')?.textContent.includes('1,013.00'));assert.ok((await f.page.locator('[data-commerce-result]').innerText()).includes('$15.00'));assert.ok(!f.square.calls.square.some(c=>/payment-links|\/v2\/payments/.test(c.path)));assert.deepEqual(f.errors,[]);await f.context.close();});
await test('five-language mobile preparation has readable labels and no horizontal overflow',async()=>{for(const lang of ['en','tr','es','de','fr']){const f=await fixture(lang,390);await f.page.locator('[data-commerce-product=coat] summary').click();await f.page.locator('[name=dispatch_days]').fill('4');const width=await f.page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(width.scroll<=width.width+1,lang+' '+JSON.stringify(width));if(lang!=='en')assert.ok(!(await f.page.locator('.commerce').innerText()).includes('Save preparation'));assert.deepEqual(f.errors,[]);if(lang==='en'){fs.mkdirSync('/private/tmp/commerce-qa',{recursive:true});await f.page.screenshot({path:'/private/tmp/commerce-qa/mobile.png',fullPage:true});}await f.context.close();}});
console.log(`${count} commerce browser groups passed; all live services blocked`);
}finally{await browser.close();}
