import assert from 'node:assert/strict';import '../assets/ms-commerce.js';import {catalogService} from './catalog-service-fixture.mjs';
const C=globalThis.MsCommerce;let count=0;const test=async(name,fn)=>{await fn();console.log('PASS '+name);count++;};
const item={id:'jeans',name:'Jeans',variations:[{id:'j',name:'M',price:14995,currency:'USD',track:true,stock:3}]},belt={id:'belt',name:'Belt',variations:[{id:'b',name:'Regular',price:7900,currency:'USD',track:true,stock:1}]};
function setup(){const s=C.blank();Object.assign(s,{countries:['US'],pickup:true,mode:'flat',origin_country:'US',origin_postal:'90291',dispatch_days:3,returns_url:'https://example.test/returns',tax_reviewed:true});for(const p of C.profiles)s.rates[p]={base:1200,extra:300};s.rates.light={base:600,extra:100};for(const [id,profile] of [['jeans','standard'],['belt','light']])s.products[id]={sale:'ready',profile,weight_g:null,length_cm:null,width_cm:null,height_cm:null};return s;}
await test('new sites start without guessed regions, tariffs, weights or live payments',()=>{const s=C.blank();assert.deepEqual(s.countries,[]);assert.equal(s.rates.standard.base,null);assert.equal(C.readiness(s,null,null,[]).checkout_live,false);});
await test('setup validation rejects foreign products, decimals, unsafe policy URLs and negative tariffs',()=>{for(const alter of [s=>s.products.foreign=s.products.jeans,s=>s.rates.standard.base=-1,s=>s.rates.standard.extra=1.5,s=>s.returns_url='javascript:alert(1)',s=>s.products.jeans.weight_g=0,s=>s.countries=['ZZ']]){const s=setup();alter(s);assert.throws(()=>C.validate(s,new Set(['jeans','belt'])),/commerce_invalid/);}});
await test('mixed parcels charge one highest base plus other unit fees regardless of cart order',()=>{const s=setup(),lines=[{variation:'j',quantity:2},{variation:'b',quantity:1}],a=C.quote(s,[item,belt],{lines,delivery:'ship',country:'US'},'USD'),b=C.quote(s,[item,belt],{lines:[...lines].reverse(),delivery:'ship',country:'US'},'USD');assert.equal(a.shipping,1600);assert.equal(a.total_before_tax,39490);assert.equal(a.shipping,b.shipping);assert.equal(a.tax,'pending_square');assert.equal(a.preview_only,true);});
await test('pickup is zero shipping; unset rates are not treated as free shipping',()=>{const s=setup();s.mode='pending';assert.equal(C.quote(s,[item],{delivery:'pickup',lines:[{variation:'j',quantity:1}]},'USD').shipping,0);assert.throws(()=>C.quote(s,[item],{delivery:'ship',country:'US',lines:[{variation:'j',quantity:1}]},'USD'),/shipping_pending/);s.mode='flat';s.rates.standard.base=null;assert.throws(()=>C.quote(s,[item],{delivery:'ship',country:'US',lines:[{variation:'j',quantity:1}]},'USD'),/shipping_pending/);});
await test('quotes reject regions, tampered prices, duplicate quantities beyond stock and untracked products',()=>{const s=setup(),base={delivery:'ship',country:'US',lines:[{variation:'j',quantity:1,price:1}]};assert.equal(C.quote(s,[item],base,'USD').subtotal,14995);assert.throws(()=>C.quote(s,[item],{...base,country:'CA'},'USD'),/delivery/);assert.throws(()=>C.quote(s,[item],{...base,lines:[{variation:'j',quantity:2},{variation:'j',quantity:2}]},'USD'),/unavailable/);assert.throws(()=>C.quote(s,[{...item,variations:[{...item.variations[0],track:false,stock:null}]}],base,'USD'),/unavailable/);assert.throws(()=>C.quote(s,[item],base,'CAD'),/unavailable/);});
await test('complete preparation still never enables live checkout',()=>{const r=C.readiness(setup(),{},C.permissions,[item,belt]);assert.equal(r.setup_ready,true);assert.equal(r.checkout_live,false);});
await test('anonymous, active viewers and wrong-site accounts cannot read or save preparation',async()=>{for(const kind of ['anon','viewer','wrong']){const f=catalogService();if(kind!=='anon'){f.state.admin=false;f.state.viewer=kind==='viewer';f.state.member=true;}const r=await f.post({action:'commerce_status',site:kind==='wrong'?'heron':'rufcut'},kind!=='anon');assert.equal(r.status,403);assert.equal(f.calls.square.length,0);assert.equal(f.calls.writes.length,0);}});
await test('the real handler isolates Heron and Rufcut setup and only requests payment scopes explicitly',async()=>{const f=catalogService();let d=await(await f.post({action:'commerce_status'})).json();assert.equal(d.readiness.checkout_live,false);assert.ok(d.readiness.blockers.includes('payment_permissions'));const s=C.blank();s.countries=['US'];s.pickup=true;assert.equal((await f.post({action:'commerce_save',setup:s})).status,200);assert.deepEqual((await(await f.post({action:'commerce_status'})).json()).setup.countries,['US']);assert.deepEqual((await(await f.post({action:'commerce_status',site:'heron'})).json()).setup.countries,[]);assert.equal((await(await f.post({action:'commerce_status',site:'heron'})).json()).currency,null);for(const commerce of [false,true]){const r=await f.post({action:'connect',commerce});assert.equal(r.status,200);const url=new URL((await r.json()).url),scopes=url.searchParams.get('scope').split(' ');assert.equal(scopes.includes('PAYMENTS_WRITE'),commerce);assert.equal(scopes.includes('ORDERS_WRITE'),commerce);assert.ok(scopes.includes('ITEMS_READ'));}assert.ok(!f.calls.square.some(c=>/payment-links|\/v2\/payments/.test(c.path)));});
await test('real handler only quotes approved shop variations and never writes Square during preparation',async()=>{const f=catalogService(),s=C.blank();s.pickup=true;s.products.coat={sale:'ready',profile:'standard',weight_g:null,length_cm:null,width_cm:null,height_cm:null};await f.post({action:'save_publication',item:'coat',publication:{section:'shop',layout:'grouped',title:'',variations:{s:{visible:true,title:''},m:{visible:false,title:''}}}});await f.post({action:'commerce_save',setup:s});const ok=await f.post({action:'commerce_quote',quote:{delivery:'pickup',lines:[{variation:'s',quantity:1}]}});assert.equal(ok.status,200);assert.equal((await ok.json()).subtotal,49900);assert.equal((await f.post({action:'commerce_quote',quote:{delivery:'pickup',lines:[{variation:'m',quantity:1}]}})).status,400);assert.ok(f.calls.square.every(c=>c.path==='/v2/catalog/list'||c.path.includes('batch-retrieve')));});
console.log(`${count} commerce checks passed; no live payment, rate or label calls`);
