// Local-only photo preparation and series controls; all non-preview requests blocked.
import assert from 'node:assert/strict';import fs from 'node:fs';import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL(process.env.MS_PLAYWRIGHT_MODULE)),origin=process.env.MS_PREVIEW_ORIGIN||'http://127.0.0.1:4174';
fs.mkdirSync('/private/tmp/rufcut-fitting-media',{recursive:true});
const browser=await chromium.launch({executablePath:process.env.MS_CHROME_PATH,headless:true});let count=0;
async function fixture(lang='en',width=1280){const page=await browser.newPage({viewport:{width,height:900},reducedMotion:'reduce'});await page.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await page.goto(origin+'/404.html');await page.setContent(`<html lang="${lang}"><head></head><body><button id="open">Photo</button><figure style="width:300px;position:relative"><img id="picture" data-ms-field="test.photo" src="${origin}/rufcut/media/rufcut-store.webp" srcset="${origin}/rufcut/media/rufcut-store-576.webp 576w" sizes="300px" alt="Original photograph" style="width:100%"></figure></body></html>`);for(const file of ['ms-photo-studio','ms-photo-deck']){await page.addStyleTag({url:origin+'/assets/'+file+'.css'});await page.addScriptTag({url:origin+'/assets/'+file+'.js'});}await page.evaluate(origin=>{document.querySelector('#open').onclick=async()=>{try{const response=await fetch(origin+'/rufcut/media/rufcut-store.webp'),blob=await response.blob(),file=new File([blob],'workshop.webp',{type:'image/webp'});window.result=await MsPhotoStudio.open(file,{ratio:16/9});if(window.result){const image=new Image();image.src=URL.createObjectURL(window.result);await image.decode();window.exported={type:window.result.type,bytes:window.result.size,width:image.naturalWidth,height:image.naturalHeight};URL.revokeObjectURL(image.src);}}catch(e){window.error=e.message;}};},origin);return page;}
try{
 let p=await fixture();await p.locator('#open').click();await p.locator('.ms-photo-studio[open]').waitFor();await p.locator('[data-photo-range=zoom]').fill('1.4');await p.locator('[data-photo-range=brightness]').fill('115');await p.locator('[data-photo-rotate]').click();await p.screenshot({path:'/private/tmp/rufcut-fitting-media/photo-studio.png'});await p.locator('[data-photo-use]').click();await p.waitForFunction(()=>window.exported);const output=await p.evaluate(()=>exported);assert.equal(output.type,'image/webp');assert.equal(output.width,1600);assert.equal(output.height,900);assert.ok(output.bytes>1000&&output.bytes<5*1024*1024);assert.equal(await p.locator('dialog').count(),0);await p.close();console.log('PASS crop/rotate/adjust exports a bounded real-photo WebP');count++;
 p=await fixture();await p.locator('#open').click();await p.locator('[data-photo-range=zoom]').fill('2');await p.locator('[data-photo-reset]').click();assert.equal(await p.locator('[data-photo-range=zoom]').inputValue(),'1');await p.locator('dialog').press('Escape');assert.equal(await p.locator('dialog').count(),0);assert.equal(await p.evaluate(()=>window.exported||null),null);await p.close();console.log('PASS reset and cancel keep the source photo untouched');count++;
 for(const lang of ['en','tr','es','de','fr']){p=await fixture(lang,390);await p.locator('#open').click();await p.locator('dialog[open]').waitFor();assert.ok(await p.locator('dialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1),lang+' dialog overflow');assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),lang+' page overflow');await p.locator('[data-photo-cancel]').last().click();await p.close();}console.log('PASS photo controls fit mobile in all five languages');count++;
 p=await fixture();const result=await p.evaluate(origin=>{const image=document.querySelector('#picture'),original={src:image.src,srcset:image.getAttribute('srcset'),sizes:image.getAttribute('sizes'),alt:image.alt};const config={version:1,slides:[{url:origin+'/rufcut/media/rufcut-store.webp',alt:'Shop'},{url:origin+'/rufcut/media/rufcut-detail.webp',alt:'Bench'}]};const mounted=MsPhotoDeck.mount(image,config);return {mounted,original,field:image.dataset.msField,direct:image.parentElement.tagName};},origin);assert.equal(result.mounted,true);assert.equal(result.field,'test.photo');assert.equal(result.direct,'FIGURE');await p.getByRole('button',{name:'Next photo',exact:true}).click();assert.equal(await p.locator('#picture').getAttribute('alt'),'Bench');await p.getByRole('button',{name:'Previous photo',exact:true}).click();assert.equal(await p.locator('#picture').getAttribute('alt'),'Shop');assert.equal(await p.locator('.ms-photo-deck-controls button').first().evaluate(el=>el.getBoundingClientRect().height),44);
 const restored=await p.evaluate(()=>{const image=document.querySelector('#picture');MsPhotoDeck.destroy(image,true);return {src:image.src,srcset:image.getAttribute('srcset'),sizes:image.getAttribute('sizes'),alt:image.alt};});assert.deepEqual(restored,result.original);assert.equal(await p.locator('.ms-photo-deck-controls').count(),0);const oldSeries=await p.evaluate(origin=>{const img=document.querySelector('#picture'),old={version:1,slides:[{url:origin+'/rufcut/media/rufcut-store.webp',alt:'Existing shop'},{url:origin+'/rufcut/media/rufcut-detail.webp',alt:'Existing bench'}]};img.dataset.msSlides=JSON.stringify(old);MsPhotoDeck.mount(img,old);MsPhotoDeck.mount(img,{version:1,slides:[{url:origin+'/rufcut/media/rufcut-detail.webp',alt:'Replacement'}]});MsPhotoDeck.destroy(img,true);return JSON.parse(img.dataset.msSlides);},origin);assert.equal(oldSeries.slides[0].alt,'Existing shop');await p.getByRole('button',{name:'Next photo',exact:true}).click();assert.equal(await p.locator('#picture').getAttribute('alt'),'Existing bench');await p.close();console.log('PASS series navigates without replacing the editor image and restores source attributes');count++;
 p=await fixture();assert.equal(await p.evaluate(()=>MsPhotoDeck.parse({version:1,slides:[{url:'javascript:alert(1)',alt:'x'}]})),null);assert.equal(await p.evaluate(()=>MsPhotoDeck.parse({version:1,slides:[{url:'https://user:password@example.test/photo.jpg',alt:'x'}]})),null);assert.equal(await p.evaluate(()=>MsPhotoDeck.parse({version:1,slides:Array.from({length:7},()=>({url:'https://example.test/photo.jpg',alt:'x'}))})),null);await p.close();console.log('PASS series rejects executable URLs, embedded credentials and excess photos');count++;
 p=await browser.newPage({viewport:{width:390,height:844}});const requests=[];let fail=true;await p.route('**/*',async route=>{const req=route.request(),url=new URL(req.url());if(url.origin===origin)return route.continue();if(url.pathname.endsWith('ms-repair')){const data=req.postDataJSON();requests.push(data);return route.fulfill({status:fail?503:200,contentType:'application/json',body:JSON.stringify(fail?{error:'unavailable'}:{ticket:'RC-TEST234',kind:'fitting'})});}return route.abort();});await p.goto(origin+'/rufcut/fitting/?lang=en');await p.locator('[name=name]').fill('Test fitting');await p.locator('[name=email]').fill('fitting@example.test');const date=await p.locator('[name=preferred_date]').getAttribute('min');await p.locator('[name=preferred_date]').fill(date);await p.screenshot({path:'/private/tmp/rufcut-fitting-media/fitting-form.png'});await p.locator('[type=submit]').click();await p.locator('#fittingStatus').filter({hasText:'couldn’t send'}).waitFor();assert.equal(await p.locator('[name=name]').inputValue(),'Test fitting');fail=false;await p.locator('[type=submit]').click();await p.locator('.fitting-code').waitFor();assert.equal(await p.locator('.fitting-code').innerText(),'RC-TEST234');assert.equal(requests[0].action,'submit_fitting');assert.equal(requests[0].token,requests[1].token);assert.equal(requests[0].preferred_date,date);assert.ok((await p.locator('.fitting-receipt').innerText()).includes('confirm a day and time'));await p.close();console.log('PASS fitting form retains a failed request and reuses its submission token');count++;
 for(const lang of ['en','tr','es','de','fr']){p=await browser.newPage({viewport:{width:390,height:844}});await p.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());await p.goto(origin+'/rufcut/fitting/?lang='+lang);assert.equal(await p.locator('html').getAttribute('lang'),lang);for(const theme of ['dark','light']){await p.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),lang+' fitting form overflow');}await p.close();}console.log('PASS fitting request form fits mobile in all five languages');count++;
 console.log(`${count} fitting/media browser groups passed; no uploads or live API calls`);
}finally{await browser.close();}
