import assert from 'node:assert/strict';import fs from 'node:fs';import {pathToFileURL} from 'node:url';import {catalogService} from './catalog-service-fixture.mjs';import {service} from './order-service-fixture.mjs';
const {chromium}=await import(pathToFileURL(process.env.MS_PLAYWRIGHT_MODULE)),browser=await chromium.launch({executablePath:process.env.MS_CHROME_PATH,headless:true}),origin=process.env.MS_PREVIEW_ORIGIN||'http://127.0.0.1:4174';
let count=0;const test=async(name,fn)=>{await fn();console.log('PASS '+name);count++;};
async function fixture(lang='en',width=1280){const context=await browser.newContext({locale:lang,viewport:{width,height:1000},reducedMotion:'reduce'}),square=catalogService(),orders=service(),notifications=service('notifications'),errors=[];square.state.objects[0].image_data.url=origin+'/rufcut/media/rufcut-detail.webp';
await context.addInitScript(lang=>{localStorage.setItem('ms_lang',lang);localStorage.setItem('ms_panel',JSON.stringify({access_token:'test-session',expires_at:Date.now()/1000+3600,email:'owner@example.test'}));},lang);
await context.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(u.origin===origin)return route.continue();if(!u.hostname.endsWith('.supabase.co'))return route.abort();
if(u.pathname.includes('ms-square')){const r=u.pathname.endsWith('/public')?await square.publicCatalog():await square.post(req.postDataJSON());return route.fulfill({status:r.status,body:await r.text(),contentType:'application/json'});}
if(u.pathname.endsWith('ms-repair')||u.pathname.endsWith('ms-notifications')){const r=await(u.pathname.endsWith('ms-repair')?orders:notifications).post(req.postDataJSON(),{auth:true});return route.fulfill({status:r.status,body:await r.text(),contentType:'application/json'});}
return route.fulfill({contentType:'application/json',body:JSON.stringify(u.pathname.endsWith('ms_my_sites')?[{slug:'rufcut',name:'Rufcut',url:origin+'/rufcut/'}]:{sites:[]})});});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000);return {context,page,square,errors};}
try{
 await test('first entry shows guide, opt-out checkbox is at the bottom and help stays accessible',async()=>{const f=await fixture();await f.page.goto(origin+'/panel/?site=rufcut');await f.page.locator('.cat-help').waitFor();assert.equal(await f.page.locator('.cat-help footer [data-help-skip]').count(),1);await f.page.locator('[data-help-skip]').check();await f.page.locator('[data-help-continue]').click();await f.page.locator('.order-inbox').waitFor();await f.page.reload();await f.page.locator('.order-inbox').waitFor();assert.equal(await f.page.locator('.cat-help').count(),0);await f.page.locator('[data-v=help]').click();await f.page.locator('.cat-help').waitFor();await f.page.locator('[data-help-skip]').uncheck();await f.page.locator('[data-help-continue]').click();await f.page.reload();await f.page.locator('.cat-help').waitFor();assert.deepEqual(f.errors,[]);await f.context.close();});
 await test('placement preview, save and draft preservation work through real handler',async()=>{const f=await fixture();await f.page.goto(origin+'/panel/?site=rufcut&view=catalog');const item=f.page.locator('[data-cat-item=coat]');await item.waitFor();await item.locator('summary').click();const form=item.locator('form');await form.locator('[name=section]').selectOption('shop');await form.locator('[name=category]').selectOption('outerwear');await form.locator('[name=display_order]').fill('25');await form.locator('[data-variant-row=s] [type=checkbox]').check();await form.locator('[data-variant-row=m] [type=checkbox]').check();assert.equal(await form.locator('.cat-preview-card').count(),1);await f.page.locator('[data-v=stock]').click();await f.page.locator('[data-v=catalog]').click();assert.equal(await f.page.locator('[data-cat-item=coat] [name=section]').inputValue(),'shop');await f.page.locator('[data-cat-item=coat] [name=confirm]').check();await f.page.locator('[data-cat-item=coat] [type=submit]').click();await f.page.waitForFunction(()=>document.querySelector('[data-cat-item=coat] summary small')?.textContent.includes('Shop'));assert.equal(f.square.state.rules.length,1);assert.equal(f.square.state.rules[0].category,'outerwear');assert.equal(f.square.state.rules[0].display_order,25);assert.equal((await(await f.square.publicCatalog()).json()).items.length,1);assert.deepEqual(f.errors,[]);await f.context.close();});
 await test('save errors keep changes and show an inline message',async()=>{const f=await fixture();await f.page.goto(origin+'/panel/?site=rufcut&view=catalog');const item=f.page.locator('[data-cat-item=coat]');await item.locator('summary').click();await item.locator('[name=section]').selectOption('shop');await item.locator('[data-variant-row=s] [type=checkbox]').check();await item.locator('[name=confirm]').check();f.square.state.failSave=true;await item.locator('[type=submit]').click();await f.page.waitForFunction(()=>document.querySelector('[data-cat-error]')?.textContent.includes('Could not save'));assert.equal(await item.locator('[name=section]').inputValue(),'shop');assert.equal(f.square.state.rules.length,0);assert.deepEqual(f.errors,[]);await f.context.close();});
 await test('new item form names destination; add variation preserves its product',async()=>{const f=await fixture();await f.page.goto(origin+'/panel/?site=rufcut&view=catalog');await f.page.locator('[data-act=add]').click();assert.equal(await f.page.locator('#dlgForm [name=section]').inputValue(),'review');await f.page.locator('#dlgForm [name=name]').fill('Test new jeans');await f.page.locator('#dlgForm [name=price]').fill('149');await f.page.locator('#dlgForm [name=category]').selectOption('jeans');await f.page.locator('#dlgForm [name=display_order]').fill('10');await f.page.locator('#dlgForm [type=submit]').click();await f.page.locator('#dlg').waitFor({state:'hidden'});assert.equal(f.square.state.rules.find(r=>r.item_id.startsWith('new-')).section,'review');assert.equal(f.square.state.rules.find(r=>r.item_id.startsWith('new-')).category,'jeans');const item=f.page.locator('[data-cat-item=coat]');await item.locator('summary').click();await item.locator('[data-cat-add-variant]').click();await f.page.locator('#dlgForm [name=variant]').fill('XL');await f.page.locator('#dlgForm [name=price]').fill('499');await f.page.locator('#dlgForm [type=submit]').click();await f.page.locator('#dlg').waitFor({state:'hidden'});assert.equal(f.square.state.objects.find(i=>i.id==='coat').item_data.variations.length,3);assert.deepEqual(f.errors,[]);await f.context.close();});
 await test('mobile catalog works in all five languages without horizontal overflow',async()=>{for(const lang of ['en','tr','es','de','fr']){const f=await fixture(lang,390);await f.page.goto(origin+'/panel/?site=rufcut&view=catalog');await f.page.locator('[data-cat-item=coat] summary').click();await f.page.locator('[data-cat-item=coat] [name=section]').selectOption('shop');await f.page.locator('[data-cat-item=coat] [data-variant-row=s] [type=checkbox]').check();const width=await f.page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));assert.ok(width.scroll<=width.width+1,lang+' overflow '+JSON.stringify(width));const text=await f.page.locator('[data-cat-item=coat]').innerText();if(lang!=='en')assert.ok(!text.includes('Save website placement'));assert.deepEqual(f.errors,[]);if(lang==='en'){fs.mkdirSync('/private/tmp/catalog-qa',{recursive:true});await f.page.screenshot({path:'/private/tmp/catalog-qa/mobile.png',fullPage:true});}await f.context.close();}});
 await test('storefront groups choices, shows actual selected price, and separates courses and repairs',async()=>{const f=await fixture();await f.square.post({action:'save_publication',item:'coat',publication:{section:'shop',layout:'grouped',title:'',variations:{s:{visible:true,title:''},m:{visible:true,title:''}}}});await f.square.post({action:'save_publication',item:'course',publication:{section:'workshop',layout:'grouped',title:'',variations:{'course-v':{visible:true,title:''}}}});f.square.state.objects.find(i=>i.id==='coat').item_data.variations[1].item_variation_data.price_money.amount=52995;f.square.state.objects.find(i=>i.id==='coat').item_data.description='100% cotton, $499 per piece.';await f.page.goto(origin+'/rufcut/');await f.page.locator('#items .item').waitFor();assert.equal(await f.page.locator('#items .item').count(),1);assert.equal(await f.page.locator('#mf').isVisible(),false);await f.page.locator('#items select').selectOption('1');assert.ok((await f.page.locator('#items [data-store-price]').innerText()).includes('529.95'));assert.equal(await f.page.locator('#workshopOffers .item').count(),1);assert.equal(await f.page.locator('#items').getByText('Jean Workshop').count(),0);assert.deepEqual(f.errors,[]);await f.context.close();});
 await test('jeans lead the shop; Accessories contains Belt and excludes workshop and repair services',async()=>{const f=await fixture('en',390);
 for(const [name,section,category,display_order] of [['Belt','shop','accessories',0],['My jeans','shop','jeans',10],['AAA repair','repair','jeans',0],['Workshop','workshop','jeans',0]])await f.square.post({action:'add_item',name,section,category,display_order,price:79,qty:1,track:false,submission_token:crypto.randomUUID()});
 await f.page.goto(origin+'/rufcut/');await f.page.locator('#items .item').first().waitFor();assert.deepEqual(await f.page.locator('#items .item h3').allTextContents(),['My jeans','Belt']);assert.deepEqual(await f.page.locator('.shop-group-title').allTextContents(),['Jeans & overalls','Accessories']);
 await f.page.locator('#cf [data-category=accessories]').click();assert.deepEqual(await f.page.locator('#items .item h3').allTextContents(),['Belt']);assert.equal(await f.page.locator('#cf [data-category=accessories]').getAttribute('aria-pressed'),'true');assert.equal(await f.page.locator('#repairServices .item').count(),1);assert.equal(await f.page.locator('#workshopOffers .item').count(),1);
 const width=await f.page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));assert.ok(width.scroll<=width.width+1);await f.page.locator('#vintage').screenshot({path:'/private/tmp/catalog-qa/categories-mobile.png'});assert.deepEqual(f.errors,[]);await f.context.close();});
 console.log(`${count} catalog browser groups passed; all live services blocked`);
}finally{await browser.close();}
