import assert from 'node:assert/strict';
import {hkdfSync,verify,createPublicKey} from 'node:crypto';
import {service} from './order-service-fixture.mjs';
import {vapidKey,encryptedPush,base64url,pushEndpoint} from '../supabase/functions/_shared/web-push.ts';
let count=0;const test=async(label,fn)=>{await fn();console.log('PASS '+label);count++;};
const svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="65 35 230 430" role="img" aria-label="Jacket"><g data-cloth fill="#233b5c"><path d="M139 78 L168 65 L222 78Z"/></g><g data-action="take_in" data-active="false"><circle class="mark-ring" cx="220" cy="300" r="15" fill="#152744"/><text x="220" y="304" text-anchor="middle" fill="#ffece8" font-family="Arial,sans-serif" font-size="13" font-weight="700" pointer-events="none">1</text></g></svg>';
const payload=()=>({action:'submit',token:crypto.randomUUID(),name:'Test customer',email:'customer@example.test',items:[{garment:'jacket',gender:'unisex',actions:['take_in','patch'],marks:{take_in:[220,300],patch:[180,200]},preview_svg:svg,note:'Fit sleeve'}],preview_svg:svg});
await test('numbered jacket repair is accepted, keeps its marks and creates one durable ticket',async()=>{const f=service(),body=payload(),r=await f.post(body);assert.equal(r.status,200);assert.match((await r.json()).ticket,/^RC-[A-Z2-9]{7}$/);assert.equal(f.state.jobs.length,1);assert.deepEqual(Array.from(f.state.jobs[0].items[0].marks.take_in),[220,300]);assert.match(f.state.jobs[0].preview_svg,/<text/);assert.ok(!f.state.jobs[0].preview_svg.includes('data-action'));assert.ok(!f.state.jobs[0].preview_svg.includes('data-cloth'));assert.ok(!f.state.jobs[0].items[0].preview_svg.includes('data-cloth'));assert.equal(f.calls.fetches.length,0);});
await test('read-only validation accepts actual drawing contract without creating rows or messages',async()=>{const f=service(),r=await f.post({...payload(),action:'validate'});assert.equal(r.status,200);assert.equal(f.calls.writes.length,0);assert.equal(f.calls.fetches.length,0);});
await test('retry returns the original ticket and edited payload cannot reuse the old receipt token',async()=>{const f=service(),body=payload(),one=await(await f.post(body)).json(),two=await(await f.post(body)).json();assert.equal(one.ticket,two.ticket);assert.equal(two.duplicate,true);assert.equal(f.state.jobs.length,1);assert.equal((await f.post({...body,name:'Changed customer'})).status,409);assert.equal(f.state.jobs.length,1);});
await test('failed persistence never returns a success and retry can create the same request',async()=>{const f=service(),body=payload();f.state.saveFail=true;assert.equal((await f.post(body)).status,500);assert.equal(f.state.jobs.length,0);f.state.saveFail=false;assert.equal((await f.post(body)).status,200);assert.equal(f.state.jobs.length,1);});
await test('jeans selections are stored in the same inbox; unknown choices are rejected',async()=>{const f=service(),body={...payload(),action:'submit_pair',design:{fit:'Relaxed',denim:'Raw',wash:'Narrow blue/white stripe',thread:'Pig-skin',fly:'Zip fly',hem:'Chain stitch'},measurements:'W32',note:'Fitting next week'};assert.equal((await f.post(body)).status,200);assert.equal(f.state.jobs[0].kind,'jeans');assert.equal(f.state.jobs[0].design.wash,body.design.wash);assert.equal(f.state.jobs[0].design.measurements,'W32');assert.equal((await f.post({...body,token:crypto.randomUUID(),design:{...body.design,fit:'unknown'}})).status,400);});
await test('scripts, foreign images, inline events and oversized SVG never reach storage',async()=>{for(const bad of [svg.replace('<g data-cloth','<g onload="alert(1)"'),svg.replace('</svg>','<script>alert(1)</script></svg>'),svg.replace('</svg>','<image href="https://attacker.test/pixel"/></svg>'),svg.replace('fill="#233b5c"','fill="url(https://attacker.test/x)"'),svg+' '.repeat(160001)]){const f=service();assert.equal((await f.post({...payload(),preview_svg:bad})).status,400);assert.equal(f.state.jobs.length,0);}});
await test('anonymous, viewer and unrelated member cannot read or update orders; tracking has no personal data',async()=>{
 const f=service();await f.post(payload());for(const auth of [false,true]){f.state.admin=false;f.state.member=false;assert.equal((await f.post({action:'list'},{auth})).status,401);}f.state.member=true;f.state.viewer=true;assert.equal((await f.post({action:'list'},{auth:true})).status,401);
 f.state.viewer=false;assert.equal((await f.post({action:'list'},{auth:true})).status,200);const read=f.calls.reads.find(r=>r.table==='ms_repair_jobs'&&r.columns.includes('customer_email'));assert.ok(!read.columns.includes('submission_token'));
 // Fixture mirrors selected columns only for this public read.
 const ticket=f.state.jobs[0].ticket;assert.equal((await f.post({action:'track',ticket})).status,200);assert.equal(f.calls.reads.at(-1).columns,'ticket,status,kind,created_at');
});
await test('order handlers leave transactional email to the durable SQL queue and never send directly',async()=>{const f=service();f.state.mailReady=true;f.state.emailFail=true;const body=payload();assert.equal((await f.post(body)).status,200);assert.equal(f.state.jobs.length,1);assert.equal(f.calls.fetches.length,0);await f.post(body);assert.equal(f.calls.fetches.length,0);});
await test('notification settings require site membership and return only the public signing key',async()=>{const f=service('notifications');assert.equal((await f.post({action:'settings',site:'rufcut'})).status,403);f.state.admin=false;f.state.member=true;f.state.viewer=true;assert.equal((await f.post({action:'settings',site:'rufcut'},{auth:true})).status,403);f.state.viewer=false;const r=await f.post({action:'settings',site:'rufcut'},{auth:true});assert.equal(r.status,200);const data=await r.json();assert.equal(data.publicKey.length,87);assert.equal(data.email,'shop@rufcut.com');assert.ok(!JSON.stringify(data).includes('privateJwk'));assert.ok(!JSON.stringify(data).includes('test-server-key'));});
await test('only approved browser push providers can receive push requests',async()=>{for(const endpoint of ['http://fcm.googleapis.com/x','https://127.0.0.1/x','https://fcm.googleapis.com.attacker.test/x','https://user:pw@web.push.apple.com/x','https://web.push.apple.com:4430/x'])assert.equal(pushEndpoint(endpoint),'');assert.ok(pushEndpoint('https://web.push.apple.com/test'));});
await test('encrypted push decrypts independently and its VAPID signature verifies',async()=>{
 const ua=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']),uaPub=new Uint8Array(await crypto.subtle.exportKey('raw',ua.publicKey)),auth=crypto.getRandomValues(new Uint8Array(16)),signing=await vapidKey(),payload={title:'New work order',body:'RC-TEST234',url:'https://mrspace.online/panel/?view=orders'};
 const request=await encryptedPush({endpoint:'https://web.push.apple.com/test',p256dh:base64url(uaPub),auth:base64url(auth)},payload,signing),body=request.body,salt=body.slice(0,16),as=body.slice(21,86);
 assert.equal(body[20],65);assert.equal(new DataView(body.buffer,body.byteOffset+16,4).getUint32(0),4096);
 const asKey=await crypto.subtle.importKey('raw',as,{name:'ECDH',namedCurve:'P-256'},false,[]),shared=await crypto.subtle.deriveBits({name:'ECDH',public:asKey},ua.privateKey,256);
 const ikm=hkdfSync('sha256',Buffer.from(shared),auth,Buffer.concat([Buffer.from('WebPush: info\0'),uaPub,as]),32);
 const cek=hkdfSync('sha256',ikm,salt,Buffer.from('Content-Encoding: aes128gcm\0'),16),nonce=hkdfSync('sha256',ikm,salt,Buffer.from('Content-Encoding: nonce\0'),12);
 const plain=new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:nonce},await crypto.subtle.importKey('raw',cek,'AES-GCM',false,['decrypt']),body.slice(86)));assert.equal(plain.at(-1),2);assert.deepEqual(JSON.parse(new TextDecoder().decode(plain.slice(0,-1))),payload);
 const jwt=request.headers.Authorization.match(/t=([^,]+)/)[1],parts=jwt.split('.'),jwk={...signing.privateJwk};delete jwk.d;assert.equal(verify('sha256',Buffer.from(parts.slice(0,2).join('.')),{key:createPublicKey({key:jwk,format:'jwk'}),dsaEncoding:'ieee-p1363'},Buffer.from(parts[2],'base64url')),true);assert.equal(JSON.parse(Buffer.from(parts[1],'base64url')).aud,'https://web.push.apple.com');
});
await test('subscription ownership, device limits and malformed keys are enforced',async()=>{
 const f=service('notifications'),ua=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']),subscription={endpoint:'https://web.push.apple.com/device',keys:{p256dh:base64url(new Uint8Array(await crypto.subtle.exportKey('raw',ua.publicKey))),auth:base64url(crypto.getRandomValues(new Uint8Array(16)))}};
 assert.equal((await f.post({action:'subscribe',site:'rufcut',subscription},{auth:true})).status,200);assert.equal(f.state.subscriptions[0].owner_email,'owner@example.test');
 f.state.user='other@example.test';await f.post({action:'unsubscribe',site:'rufcut',endpoint:subscription.endpoint},{auth:true});assert.equal(f.state.subscriptions[0].enabled,true);
 await f.post({action:'subscribe',site:'rufcut',subscription},{auth:true});assert.equal(f.state.subscriptions[0].owner_email,'other@example.test');
 await f.post({action:'unsubscribe',site:'rufcut',endpoint:subscription.endpoint},{auth:true});assert.equal(f.state.subscriptions[0].enabled,false);
 assert.equal((await f.post({action:'subscribe',site:'rufcut',subscription:{...subscription,keys:{...subscription.keys,p256dh:'bad'}}},{auth:true})).status,400);
 f.state.subscriptions=Array.from({length:10},(_,i)=>({site:'rufcut',owner_email:f.state.user,endpoint:'https://web.push.apple.com/device'+i,enabled:true}));assert.equal((await f.post({action:'subscribe',site:'rufcut',subscription},{auth:true})).status,429);
});
await test('delivery skips revoked recipients and disables expired push devices',async()=>{
 const f=service(),signing=await vapidKey(),ua=await crypto.subtle.generateKey({name:'ECDH',namedCurve:'P-256'},true,['deriveBits']);f.state.secrets.vapid=signing;f.state.pushExpire=true;f.state.subscriptions=[{site:'rufcut',owner_email:'owner@example.test',enabled:true,endpoint:'https://web.push.apple.com/device',p256dh:base64url(new Uint8Array(await crypto.subtle.exportKey('raw',ua.publicKey))),auth:base64url(crypto.getRandomValues(new Uint8Array(16))),lang:'tr'}];
 await f.post(payload());assert.equal(f.state.subscriptions[0].enabled,false);assert.equal(f.calls.fetches.length,1);
 f.state.subscriptions[0].enabled=true;f.state.admin=false;await f.post(payload());assert.equal(f.state.subscriptions[0].enabled,false);assert.equal(f.calls.fetches.length,1);
});
await test('public readiness reports only booleans and saved status survives mail delivery failure',async()=>{
 const n=service('notifications');assert.deepEqual(await(await n.post({action:'capabilities'})).json(),{emailReady:false,pushReady:false});
 const f=service();f.state.mailReady=true;f.state.emailFail=true;await f.post(payload());const job=f.state.jobs[0];assert.equal((await f.post({action:'update',id:job.id,status:'ready',staff_notes:'Confirmed pickup',measurements:'W32'},{auth:true})).status,200);assert.equal(job.status,'ready');assert.equal(job.staff_notes,'Confirmed pickup');
});
await test('older saved HTML-style drawings are normalized when opened in the inbox',async()=>{
 const f=service();await f.post(payload());f.state.jobs[0].preview_svg=svg;f.state.jobs[0].items[0].preview_svg=svg;
 const data=await(await f.post({action:'list'},{auth:true})).json();assert.ok(!data.jobs[0].preview_svg.includes('data-cloth'));assert.ok(!data.jobs[0].items[0].preview_svg.includes('data-cloth'));
});
console.log(`${count} work-order and push checks passed; no live messages sent`);
