-- Ortak hizmet platformu. Kaynak SQL; canlıya uygulanmadı.
-- Önkoşul: mrspace-system, mrspace-access, mrspace-square, requests-v2.
-- Aynı transaction içinde çalıştırılır; tekrar çalıştırmak kayıtları sıfırlamaz.
begin;

-- Yeni müşteri başvuruları, site anahtarı edinmeden önce özel operatör kuyruğuna girer.
create table if not exists public.ms_intakes (
  id bigint generated by default as identity primary key,
  token uuid not null unique,
  name text not null,
  business text not null,
  email text,
  phone text,
  sector text not null,
  answers jsonb not null,
  sender_hash text not null,
  status text not null default 'new' check(status in('new','reviewing','accepted','closed')),
  operator_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.ms_intakes enable row level security;
revoke all on public.ms_intakes from public,anon,authenticated;
grant all on public.ms_intakes to service_role;
grant usage,select on sequence public.ms_intakes_id_seq to service_role;
create index if not exists ms_intakes_sender_idx on public.ms_intakes(sender_hash,created_at);

create or replace function public.ms_submit_intake(p_token uuid,p_name text,p_business text,p_email text,p_phone text,p_sector text,p_answers jsonb,p_sender_hash text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_id bigint;
begin
  if p_token is null or length(trim(coalesce(p_name,''))) not between 2 and 120
    or length(trim(coalesce(p_business,''))) not between 2 and 120
    or p_sender_hash is null or p_sender_hash !~ '^[a-f0-9]{64}$'
    or p_answers is null or jsonb_typeof(p_answers)<>'object' or octet_length(p_answers::text)>20000
    or length(coalesce(p_email,''))>200 or length(coalesce(p_phone,''))>80
    or (nullif(trim(p_email),'') is null and length(trim(coalesce(p_phone,'')))<5)
    or (nullif(trim(p_phone),'') is not null and (p_phone !~ '^[+0-9().[:space:]-]{5,80}$' or length(regexp_replace(p_phone,'[^0-9]','','g'))<5))
    or (nullif(trim(p_email),'') is not null and p_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$')
    or p_sector is null or p_sector not in('general','retail','fashion','food','services','community') then raise exception 'invalid_application'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(p_sender_hash,71823));
  select id into v_id from public.ms_intakes where token=p_token;
  if v_id is not null then return jsonb_build_object('ok',true,'id',v_id,'duplicate',true); end if;
  if (select count(*) from public.ms_intakes where sender_hash=p_sender_hash and created_at>now()-interval '1 hour')>=5 then raise exception 'too_many'; end if;
  insert into public.ms_intakes(token,name,business,email,phone,sector,answers,sender_hash)
  values(p_token,trim(p_name),trim(p_business),nullif(trim(p_email),''),nullif(trim(p_phone),''),p_sector,p_answers,p_sender_hash)
  returning id into v_id;
  return jsonb_build_object('ok',true,'id',v_id,'duplicate',false);
end $$;
revoke all on function public.ms_submit_intake(uuid,text,text,text,text,text,jsonb,text) from public,anon,authenticated;
grant execute on function public.ms_submit_intake(uuid,text,text,text,text,text,jsonb,text) to service_role;

create or replace function public.ms_intake_list()
returns jsonb language plpgsql security definer set search_path = '' as $$
begin
  if auth.uid() is null or not public.ms_is_admin() then raise exception 'not_admin'; end if;
  return coalesce((select jsonb_agg(to_jsonb(i)-'token'-'sender_hash' order by i.created_at desc)
    from (select * from public.ms_intakes order by created_at desc limit 100)i),'[]');
end $$;
revoke all on function public.ms_intake_list() from public,anon,authenticated;
grant execute on function public.ms_intake_list() to authenticated;

create or replace function public.ms_handle_intake(p_id bigint,p_status text,p_note text default null)
returns void language plpgsql security definer set search_path = '' as $$
begin
  if auth.uid() is null or not public.ms_is_admin() then raise exception 'not_admin'; end if;
  if p_status is null or p_status not in('new','reviewing','accepted','closed') or length(coalesce(p_note,''))>2000 then raise exception 'invalid_status'; end if;
  update public.ms_intakes set status=p_status,operator_note=nullif(trim(p_note),''),updated_at=now() where id=p_id;
  if not found then raise exception 'not_found'; end if;
end $$;
revoke all on function public.ms_handle_intake(bigint,text,text) from public,anon,authenticated;
grant execute on function public.ms_handle_intake(bigint,text,text) to authenticated;

create table if not exists public.ms_site_profiles (
  site text primary key references public.ms_sites(slug),
  service_package text not null default 'package_1'
    check (service_package in ('platform','package_1','package_2','package_3')),
  sector text not null default 'general'
    check (sector in ('general','retail','fashion','food','services','community')),
  relationship text not null default 'client'
    check (relationship in ('platform','portfolio','product','client')),
  showcase boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.ms_service_connections (
  site text not null references public.ms_sites(slug),
  service text not null check (service in ('heron','laloo','square','builder','repair','requests','worker')),
  state text not null default 'setup' check (state in ('setup','connected','error')),
  checked_at timestamptz,
  error_code text check (error_code is null or error_code ~ '^[a-z0-9_]{1,80}$'),
  primary key (site,service)
);

-- Tekrarlanan gönderimin aynı talebi döndürmesini sağlayan teslim kaydı.
-- İçeriği kimseye açılmaz, yalnızca güvenilir RPC kullanır.
create table if not exists public.ms_request_receipts (
  site text not null references public.ms_sites(slug),
  token uuid not null,
  change_id bigint not null references public.ms_changes(id),
  created_at timestamptz not null default now(),
  primary key (site,token)
);

create table if not exists public.ms_draft_jobs (
  id bigint generated by default as identity primary key,
  sector text not null check (sector in ('general','retail','fashion','food','services','community')),
  kind text not null check (kind in ('design','tool')),
  brief text not null check (length(brief) between 10 and 2000),
  status text not null default 'queued'
    check (status in ('queued','working','review','ready','rejected','failed')),
  artifact_path text,
  pr_url text,
  error_code text,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  reviewed_at timestamptz,
  reviewed_by uuid,
  token uuid not null unique
);
create index if not exists ms_draft_jobs_queue_idx on public.ms_draft_jobs(status,created_at);
alter table public.ms_draft_jobs add column if not exists artifact_html text
  check(artifact_html is null or length(artifact_html)<=1000000);
create index if not exists ms_site_users_site_idx on public.ms_site_users(site);
grant usage,select on sequence public.ms_draft_jobs_id_seq to service_role;

alter table public.ms_changes add column if not exists pr_head_sha text;
alter table public.ms_changes add column if not exists pr_url text;
alter table public.ms_changes add column if not exists ai_status text;
alter table public.ms_changes add column if not exists ai_attempts int not null default 0;
alter table public.ms_changes add column if not exists ai_at timestamptz;
grant select,update on public.ms_changes to service_role;
create table if not exists public.ms_change_reviews (
  change_id bigint primary key references public.ms_changes(id),
  decision text not null default 'pending' check(decision in ('pending','approved','revision_requested')),
  proposed text not null default '',
  selector text,
  note text,
  reviewed_sha text,
  reviewed_at timestamptz,
  released_at timestamptz,
  updated_at timestamptz not null default now()
);
alter table public.ms_change_reviews enable row level security;
revoke all on public.ms_change_reviews from public,anon,authenticated;
grant select on public.ms_change_reviews to authenticated;
grant all on public.ms_change_reviews to service_role;
do $$ begin
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='ms_change_reviews' and policyname='ms_platform_admin_read') then
    create policy ms_platform_admin_read on public.ms_change_reviews for select to authenticated using(public.ms_is_admin());
  end if;
end $$;

do $$ declare t text; begin
  foreach t in array array['ms_site_profiles','ms_service_connections','ms_request_receipts','ms_draft_jobs'] loop
    execute format('alter table public.%I enable row level security',t);
    execute format('revoke all on public.%I from public,anon,authenticated',t);
    execute format('grant all on public.%I to service_role',t);
  end loop;
end $$;

-- Operatör, RLS ile bile bağlantıyı "çalışıyor" diye elle işaretleyemez.
-- Durum sadece service-role bağlantı kontrolünden gelir.
grant select on public.ms_site_profiles,public.ms_service_connections,public.ms_draft_jobs to authenticated;
do $$ begin
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='ms_site_profiles' and policyname='ms_platform_admin_read') then
    create policy ms_platform_admin_read on public.ms_site_profiles for select to authenticated using(public.ms_is_admin());
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='ms_service_connections' and policyname='ms_platform_admin_read') then
    create policy ms_platform_admin_read on public.ms_service_connections for select to authenticated using(public.ms_is_admin());
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='ms_draft_jobs' and policyname='ms_platform_admin_read') then
    create policy ms_platform_admin_read on public.ms_draft_jobs for select to authenticated using(public.ms_is_admin());
  end if;
end $$;

insert into public.ms_site_profiles(site,service_package,sector,relationship,showcase)
select s.slug,v.package,v.sector,v.relationship,v.showcase
from public.ms_sites s join (values
  ('mrspace','platform','services','platform',false),
  ('heron','package_3','retail','portfolio',true),
  ('laloo','package_3','community','product',true),
  ('rufcut','package_3','fashion','client',false)
) v(slug,package,sector,relationship,showcase) on s.slug=v.slug
on conflict(site) do nothing;

-- Kamuya veya izleyiciye açılmayan, tek site sınırı.
create or replace function public.ms_workspace_allowed(p_site text)
returns boolean language sql stable security definer set search_path = '' as $$
  select auth.uid() is not null and coalesce(public.ms_role(),'client')<>'viewer' and (public.ms_is_admin() or exists(
    select 1 from public.ms_site_users u where u.site=p_site
      and u.email=lower(coalesce(auth.jwt()->>'email',''))
  ));
$$;
revoke all on function public.ms_workspace_allowed(text) from public,anon,authenticated;
grant execute on function public.ms_workspace_allowed(text) to authenticated,service_role;

-- Eski müşteri paneli RPC'si de viewer hesabına UUID yazma yetkisi sızdırmaz.
create or replace function public.ms_my_sites()
returns json language sql stable security definer set search_path = '' as $$
  select coalesce(json_agg(json_build_object(
    'slug',s.slug,'name',s.name,'url',s.url,'plan',s.plan,'status',s.status,'site_key',s.site_key,
    'square',(select json_build_object('location',q.location_name,'public',q.public_catalog,'since',q.connected_at)
      from public.ms_square q where q.site=s.slug and q.access_token is not null)
  ) order by s.name),'[]'::json)
  from public.ms_sites s where auth.uid() is not null and coalesce(public.ms_role(),'client')<>'viewer'
    and (public.ms_is_admin() or exists(select 1 from public.ms_site_users u
      where u.site=s.slug and u.email=lower(coalesce(auth.jwt()->>'email',''))));
$$;
revoke all on function public.ms_my_sites() from public,anon,authenticated;
grant execute on function public.ms_my_sites() to authenticated;

create or replace function public.ms_workspace_snapshot(p_site text default null)
returns jsonb language plpgsql stable security definer set search_path = '' as $$
declare v_admin boolean; v_sites jsonb; v_jobs jsonb;
begin
  if auth.uid() is null then raise exception 'not_allowed'; end if;
  v_admin := public.ms_is_admin();
  if p_site is not null and not public.ms_workspace_allowed(p_site) then raise exception 'not_allowed'; end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'slug',s.slug,'name',s.name,'url',s.url,'status',s.status,
    'service_package',coalesce(p.service_package,'package_1'),
    'sector',coalesce(p.sector,'general'),'relationship',coalesce(p.relationship,'client'),
    'showcase',coalesce(p.showcase,false),
    'connections',coalesce((select jsonb_agg(jsonb_build_object(
      'service',c.service,'state',c.state,'checked_at',c.checked_at,'error_code',c.error_code
    ) order by c.service) from public.ms_service_connections c where c.site=s.slug),'[]'::jsonb),
    'requests',coalesce((select jsonb_agg(jsonb_build_object(
      'id',r.id,'kind',r.kind,'target',r.target,'request',r.request,'status',r.status,
      'created_at',r.created_at,'done_at',r.done_at,
      'review_status',(select v.decision from public.ms_change_reviews v where v.change_id=r.id),
      'revision_note',(select v.note from public.ms_change_reviews v where v.change_id=r.id and v.decision='revision_requested')
    ) order by r.created_at desc) from (
      select * from public.ms_changes where site=s.slug and status<>'withdrawn' order by created_at desc limit 30
    ) r),'[]'::jsonb),
    'quota',(select to_jsonb(q) from public.ms_quota(s.slug) q)
  ) order by s.name),'[]'::jsonb) into v_sites
  from public.ms_sites s left join public.ms_site_profiles p on p.site=s.slug
  where (p_site is null or s.slug=p_site) and public.ms_workspace_allowed(s.slug);
  if v_admin then
    select coalesce(jsonb_agg(to_jsonb(j) - 'reviewed_by' - 'token' - 'artifact_html'),'[]'::jsonb) into v_jobs
    from (select * from public.ms_draft_jobs order by created_at desc limit 50) j;
  else v_jobs := '[]'::jsonb; end if;
  return jsonb_build_object('admin',v_admin,'sites',v_sites,'jobs',v_jobs);
end $$;
revoke all on function public.ms_workspace_snapshot(text) from public,anon,authenticated;
grant execute on function public.ms_workspace_snapshot(text) to authenticated;

create or replace function public.ms_workspace_link(p_key uuid)
returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object('slug',s.slug,'name',s.name,'url',s.url,'status',s.status,
    'service_package',coalesce(p.service_package,'package_1'),'sector',coalesce(p.sector,'general'))
  from public.ms_sites s left join public.ms_site_profiles p on p.site=s.slug where s.site_key=p_key;
$$;
revoke all on function public.ms_workspace_link(uuid) from public,anon,authenticated;
grant execute on function public.ms_workspace_link(uuid) to anon,authenticated;

create or replace function public.ms_set_site_profile(
  p_site text,p_package text,p_sector text,p_relationship text,p_showcase boolean
) returns void language plpgsql security definer set search_path = '' as $$
begin
  if auth.uid() is null or not public.ms_is_admin() then raise exception 'not_admin'; end if;
  if p_showcase and (p_relationship not in ('portfolio','product') or not exists(
    select 1 from public.ms_sites where slug=p_site and kind='own'
  )) then raise exception 'client_not_showcase'; end if;
  insert into public.ms_site_profiles(site,service_package,sector,relationship,showcase,updated_at)
  values(p_site,p_package,p_sector,p_relationship,p_showcase,now())
  on conflict(site) do update set service_package=excluded.service_package,sector=excluded.sector,
    relationship=excluded.relationship,showcase=excluded.showcase,updated_at=now();
  insert into public.ms_activity(site,who,action) values(p_site,'uzay','Workspace service profile updated');
end $$;
revoke all on function public.ms_set_site_profile(text,text,text,text,boolean) from public,anon,authenticated;
grant execute on function public.ms_set_site_profile(text,text,text,text,boolean) to authenticated;

-- Site üyeliği veya eski gizli talep linki. UUID token yalnızca tekrar korumasıdır;
-- tokenın kendisi bir siteye yetki vermez. Kilit eşzamanlı isteği de tekilleştirir.
create or replace function public.ms_workspace_request(
  p_site text,p_target text,p_request text,p_token uuid,p_key uuid default null
) returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_site public.ms_sites; v_id bigint; v_count integer;
begin
  if auth.uid() is not null and public.ms_role()='viewer' then raise exception 'not_allowed'; end if;
  select * into v_site from public.ms_sites where slug=p_site for update;
  if not found then raise exception 'not_allowed'; end if;
  if not public.ms_workspace_allowed(p_site) and (p_key is null or p_key is distinct from v_site.site_key) then
    raise exception 'not_allowed';
  end if;
  if p_token is null or p_target is null or p_target not in ('hours','contact','text','photo','design','general')
    or length(trim(coalesce(p_request,'')))<3 or length(p_request)>2000 then raise exception 'invalid_request'; end if;
  select change_id into v_id from public.ms_request_receipts where site=p_site and token=p_token;
  if v_id is not null then return jsonb_build_object('ok',true,'id',v_id,'duplicate',true); end if;
  if v_site.status in ('paused','suspended') then raise exception 'site_paused'; end if;
  select count(*) into v_count from public.ms_changes where site=p_site and created_at>now()-interval '1 hour';
  if v_count>=10 then raise exception 'too_many'; end if;
  insert into public.ms_changes(site,kind,target,request,requested_by)
  values(p_site,case when p_target='design' then 'big' else 'small' end,p_target,trim(p_request),'Workspace')
  returning id into v_id;
  insert into public.ms_request_receipts(site,token,change_id) values(p_site,p_token,v_id);
  insert into public.ms_activity(site,who,action) values(p_site,'client','Workspace request received');
  return jsonb_build_object('ok',true,'id',v_id,'duplicate',false);
end $$;
revoke all on function public.ms_workspace_request(text,text,text,uuid,uuid) from public,anon,authenticated;
grant execute on function public.ms_workspace_request(text,text,text,uuid,uuid) to anon,authenticated;

create or replace function public.ms_queue_draft(p_sector text,p_kind text,p_brief text,p_token uuid)
returns bigint language plpgsql security definer set search_path = '' as $$
declare v_id bigint;
begin
  if auth.uid() is null or not public.ms_is_admin() then raise exception 'not_admin'; end if;
  if p_token is null then raise exception 'invalid_token'; end if;
  perform pg_catalog.pg_advisory_xact_lock(73129410);
  select id into v_id from public.ms_draft_jobs where token=p_token;
  if v_id is not null then return v_id; end if;
  if (select count(*) from public.ms_draft_jobs where created_at>now()-interval '1 hour')>=5 then
    raise exception 'too_many';
  end if;
  insert into public.ms_draft_jobs(sector,kind,brief,token) values(p_sector,p_kind,trim(p_brief),p_token)
  returning id into v_id;
  return v_id;
end $$;
revoke all on function public.ms_queue_draft(text,text,text,uuid) from public,anon,authenticated;
grant execute on function public.ms_queue_draft(text,text,text,uuid) to authenticated;

-- Bir işçi atomik olarak en fazla bir işi alır. Eski işler sonsuz tekrar yapmaz.
create or replace function public.ms_claim_draft()
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_job public.ms_draft_jobs;
begin
  update public.ms_draft_jobs set status='failed',error_code='timeout',finished_at=now()
    where status='working' and started_at<now()-interval '15 minutes';
  select * into v_job from public.ms_draft_jobs where status='queued'
    order by created_at for update skip locked limit 1;
  if not found then return null; end if;
  update public.ms_draft_jobs set status='working',started_at=now() where id=v_job.id returning * into v_job;
  return to_jsonb(v_job)-'token'-'reviewed_by';
end $$;
revoke all on function public.ms_claim_draft() from public,anon,authenticated;
grant execute on function public.ms_claim_draft() to service_role;

-- İşçi çıktısı yayın değildir. HTML sadece operatörün script çalıştırmayan önizlemesine açılır.
create or replace function public.ms_complete_draft(p_id bigint,p_html text,p_error text default null)
returns void language plpgsql security definer set search_path = '' as $$
begin
  if p_error is null and (p_html is null or length(p_html) not between 20 and 1000000) then raise exception 'invalid_artifact'; end if;
  if p_error is not null and p_error !~ '^[a-z0-9_]{1,80}$' then raise exception 'invalid_error'; end if;
  update public.ms_draft_jobs set status=case when p_error is null then 'review' else 'failed' end,
    artifact_html=case when p_error is null then p_html else null end,error_code=p_error,finished_at=now()
    where id=p_id and status='working';
  if not found then raise exception 'not_working'; end if;
end $$;
revoke all on function public.ms_complete_draft(bigint,text,text) from public,anon,authenticated;
grant execute on function public.ms_complete_draft(bigint,text,text) to service_role;

create or replace function public.ms_draft_preview(p_id bigint)
returns text language plpgsql security definer set search_path = '' as $$
declare v_html text;
begin
  if auth.uid() is null or not public.ms_is_admin() then raise exception 'not_admin'; end if;
  select artifact_html into v_html from public.ms_draft_jobs where id=p_id and status in('review','ready');
  if v_html is null then raise exception 'not_prepared'; end if;
  return v_html;
end $$;
revoke all on function public.ms_draft_preview(bigint) from public,anon,authenticated;
grant execute on function public.ms_draft_preview(bigint) to authenticated;

create or replace function public.ms_review_draft(p_id bigint,p_status text)
returns void language plpgsql security definer set search_path = '' as $$
begin
  if auth.uid() is null or not public.ms_is_admin() then raise exception 'not_admin'; end if;
  if p_status is null or p_status not in ('ready','rejected') then raise exception 'invalid_status'; end if;
  update public.ms_draft_jobs set status=p_status,reviewed_at=now(),reviewed_by=auth.uid()
    where id=p_id and status='review';
  if not found then raise exception 'not_reviewable'; end if;
end $$;
revoke all on function public.ms_review_draft(bigint,text) from public,anon,authenticated;
grant execute on function public.ms_review_draft(bigint,text) to authenticated;

-- Önizlemede insan onayı otomatik yayın izni DEĞİLDİR.
create or replace function public.ms_review_change(p_id bigint,p_decision text,p_proposed text,p_selector text,p_note text)
returns void language plpgsql security definer set search_path = '' as $$
declare v_change public.ms_changes;
begin
  if auth.uid() is null or not public.ms_is_admin() then raise exception 'not_admin'; end if;
  if p_decision is null or p_decision not in ('pending','approved','revision_requested')
    or length(coalesce(p_proposed,''))>10000 or length(coalesce(p_selector,''))>500
    or length(coalesce(p_note,''))>2000 then raise exception 'invalid_review'; end if;
  select * into v_change from public.ms_changes where id=p_id for update;
  if not found or v_change.status in ('done','rejected','withdrawn') or v_change.ai_status='merging' then raise exception 'not_reviewable'; end if;
  if p_decision='revision_requested' and length(trim(coalesce(p_note,'')))<3 then raise exception 'note_required'; end if;
  if p_decision='approved' and (length(trim(coalesce(p_proposed,'')))<1 or length(trim(coalesce(p_selector,'')))<1) then raise exception 'preview_required'; end if;
  insert into public.ms_change_reviews(change_id,decision,proposed,selector,note,reviewed_sha,reviewed_at,released_at,updated_at)
  values(p_id,p_decision,coalesce(p_proposed,''),nullif(p_selector,''),nullif(p_note,''),v_change.pr_head_sha,
    case when p_decision<>'pending' then now() else null end,null,now())
  on conflict(change_id) do update set decision=excluded.decision,proposed=excluded.proposed,
    selector=excluded.selector,note=excluded.note,reviewed_sha=excluded.reviewed_sha,
    reviewed_at=excluded.reviewed_at,released_at=null,updated_at=now();
  insert into public.ms_activity(site,who,action) values(v_change.site,'uzay','Change review: '||p_decision);
end $$;
revoke all on function public.ms_review_change(bigint,text,text,text,text) from public,anon,authenticated;
grant execute on function public.ms_review_change(bigint,text,text,text,text) to authenticated;

-- Kullanıcının ayrıca yayın kararı; hazırlanmış PR'ın incelenen sürümü eşleşmeli.
-- Bu RPC statik yayını veya PR merge işlemini kendisi yapmaz; işçi son SHA kontrolünü yapar.
create or replace function public.ms_release_change(p_id bigint,p_expected_sha text)
returns void language plpgsql security definer set search_path = '' as $$
declare c public.ms_changes; r public.ms_change_reviews;
begin
  if auth.uid() is null or not public.ms_is_admin() then raise exception 'not_admin'; end if;
  select * into c from public.ms_changes where id=p_id for update;
  if not found or c.status not in ('new','approved') or c.ai_status is distinct from 'ready' then raise exception 'not_reviewable'; end if;
  select * into r from public.ms_change_reviews where change_id=p_id for update;
  if r.decision is distinct from 'approved' or p_expected_sha is null
    or p_expected_sha !~ '^[a-f0-9]{40}$' or c.pr_head_sha is distinct from p_expected_sha
    or r.reviewed_sha is distinct from p_expected_sha then raise exception 'review_required'; end if;
  update public.ms_change_reviews set released_at=now() where change_id=p_id;
  perform public.ms_decide_change(p_id,'approved',null);
end $$;
revoke all on function public.ms_release_change(bigint,text) from public,anon,authenticated;
grant execute on function public.ms_release_change(bigint,text) to authenticated;

-- Ayrı işçi süreçleri aynı talebe veya aynı yayın kararına sahip çıkamaz.
create or replace function public.ms_claim_request(p_id bigint)
returns boolean language plpgsql security definer set search_path = '' as $$
begin
  update public.ms_changes set ai_status='working',ai_at=now(),ai_attempts=coalesce(ai_attempts,0)+1
    where id=p_id and status='new' and ai_status is null;
  return found;
end $$;
revoke all on function public.ms_claim_request(bigint) from public,anon,authenticated;
grant execute on function public.ms_claim_request(bigint) to service_role;

create or replace function public.ms_claim_release(p_id bigint,p_sha text)
returns boolean language plpgsql security definer set search_path = '' as $$
declare c public.ms_changes; r public.ms_change_reviews;
begin
  select * into c from public.ms_changes where id=p_id for update;
  if not found or c.status<>'approved' or c.ai_status is distinct from 'ready' then return false; end if;
  select * into r from public.ms_change_reviews where change_id=p_id for update;
  if not found or r.decision<>'approved' or r.released_at is null or p_sha is null or p_sha !~ '^[a-f0-9]{40}$'
    or c.pr_head_sha is distinct from p_sha or r.reviewed_sha is distinct from p_sha then return false; end if;
  update public.ms_changes set ai_status='merging',ai_at=now() where id=p_id;
  return true;
end $$;
revoke all on function public.ms_claim_release(bigint,text) from public,anon,authenticated;
grant execute on function public.ms_claim_release(bigint,text) to service_role;

commit;
